// build-ja-map.mjs — construct the truthful EN→JA printing map (data/ja-map.js).
//
// tcgdex Japanese sets are their OWN catalogue (M2/M2a/S-series…), so there is
// no path swap: a card's Japanese printing must be FOUND. Match key =
// (national dexId, normalized illustrator): the same artwork is the same
// Pokémon drawn by the same artist. Trainers/energies (no dexId) and ambiguous
// matches are skipped — the toggle simply doesn't appear for them, and the map
// can never show the wrong card.
//
// Run: node scripts/build-ja-map.mjs      (rerun when new sets land)
'use strict';
import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const EN_SETS = ['sv01', 'sv02', 'sv03', 'sv03.5', 'sv04', 'sv04.5', 'sv05', 'sv06', 'sv06.5',
  'sv07', 'sv08', 'sv08.5', 'sv09', 'sv10', 'sv10.5b', 'sv10.5w',
  'me01', 'me02', 'me02.5', 'me03', 'me04'];

const jfetch = async (u) => {
  const r = await fetch(u, { headers: { 'User-Agent': 'Crowns-Card-Tracker/1.0' } });
  if (!r.ok) throw new Error(`${r.status} ${u}`);
  return r.json();
};
const norm = (s) => (s || '').toLowerCase().replace(/[^a-z0-9]+/g, '');

// 1) every Japanese set from the modern eras, with release dates
const jaSets = (await jfetch('https://api.tcgdex.net/v2/ja/sets'))
  .filter((s) => /^(SV|M)[0-9a-z]/i.test(s.id) || /^S[0-9]/i.test(s.id));
console.log(`ja candidate sets: ${jaSets.length}`);

// 2) index all their Pokémon cards by (dexId | illustrator)
const jaIndex = new Map();  // key -> [{img, setId}]
for (const s of jaSets) {
  let d;
  try { d = await jfetch(`https://api.tcgdex.net/v2/ja/sets/${encodeURIComponent(s.id)}`); }
  catch { continue; }
  for (const brief of d.cards || []) {
    if (!brief.image) continue;
    // brief lacks dexId/illustrator — fetch per card is too heavy; instead pull
    // the set's full cards in one go via the set endpoint? tcgdex set endpoint
    // returns briefs only, so fetch each card… cache-heavy. Compromise: fetch
    // card details ONLY for sets that pair with our eras (all filtered ones).
  }
  d._briefs = d.cards || [];
  s._detail = d;
}

// per-card detail fetches, batched with a small pool
const pool = async (items, n, fn) => {
  const out = []; let i = 0;
  await Promise.all(Array.from({ length: n }, async () => {
    while (i < items.length) { const ix = i++; out[ix] = await fn(items[ix]).catch(() => null); }
  }));
  return out;
};
let fetched = 0;
for (const s of jaSets) {
  const briefs = (s._detail && s._detail._briefs) || [];
  const details = await pool(briefs, 12, (b) => jfetch(`https://api.tcgdex.net/v2/ja/cards/${encodeURIComponent(b.id)}`));
  for (const c of details) {
    if (!c || c.category !== 'Pokemon' || !c.image) continue;
    const dex = Array.isArray(c.dexId) ? c.dexId[0] : c.dexId;
    if (!dex || !c.illustrator) continue;
    const key = dex + '|' + norm(c.illustrator);
    if (!jaIndex.has(key)) jaIndex.set(key, []);
    jaIndex.get(key).push({ img: c.image, set: s.id });
  }
  fetched += briefs.length;
  console.log(`  ja ${s.id}: indexed (${fetched} cards total)`);
}

// 3) walk the bundled EN sets and match
const map = {};
let hits = 0, misses = 0, ambiguous = 0;
for (const sid of EN_SETS) {
  let d;
  try { d = await jfetch(`https://api.tcgdex.net/v2/en/sets/${sid}`); }
  catch { console.log(`  en ${sid}: unavailable, skipped`); continue; }
  const details = await pool(d.cards || [], 12, (b) => jfetch(`https://api.tcgdex.net/v2/en/cards/${encodeURIComponent(b.id)}`));
  for (const c of details) {
    if (!c || c.category !== 'Pokemon' || !c.illustrator) { misses++; continue; }
    const dex = Array.isArray(c.dexId) ? c.dexId[0] : c.dexId;
    if (!dex) { misses++; continue; }
    const cand = jaIndex.get(dex + '|' + norm(c.illustrator)) || [];
    const uniq = [...new Set(cand.map((x) => x.img))];
    if (uniq.length === 1) { map[c.id] = uniq[0] + '/high.webp'; hits++; }
    else if (uniq.length > 1) ambiguous++;   // same artist drew this mon twice — skip, never guess
    else misses++;
  }
  console.log(`  en ${sid}: mapped so far ${hits} (ambiguous ${ambiguous}, unmatched ${misses})`);
}

const out = `// AUTO-GENERATED by scripts/build-ja-map.mjs — truthful EN→JA printing map
// (match: national dexId + illustrator across the tcgdex ja catalogue).
// Cards not in this map have no verified Japanese counterpart; the toggle hides.
window.JA_MAP = ${JSON.stringify(map)};
`;
writeFileSync(join(HERE, '..', 'data', 'ja-map.js'), out);
console.log(`\nja-map.js: ${hits} cards mapped, ${ambiguous} ambiguous skipped, ${misses} unmatched`);
